// Regenerates `.aep/index.md`, the derived discovery index.
//
// The index exists so an agent can decide what is relevant without reading
// every file, so it carries exactly the fields relevance is decided on:
// `use-when`, `mode`, and `paths`. It carries no summaries. A summary would be
// a second statement of what the artifact says, and it would drift first.
//
// Output is a pure function of the tree: rows are sorted, and the index's own
// `date` is the newest date any indexed artifact declares rather than today's,
// so regenerating an unchanged tree is byte-identical on any day. The freshness
// check in validate.mjs depends on that property.
//
//   node index.mjs [--root <path-to-.aep>] [--check]

import fs from 'node:fs';
import path from 'node:path';
import {
  readArtifact,
  resolveAepRoot,
  toPosix,
  topLevel,
  walk,
} from './contract.mjs';

// The em dash, as an escape rather than as the character itself. The rendered
// `index.md` is prose an agent reads and keeps its em dashes; the shipped
// scripts are scanned flat for the character, so it must not appear here.
const EM_DASH = '\u2014';

const GENERATED_NOTICE =
  `<!-- Generated by scripts/index.mjs ${EM_DASH} do not edit; run the script. -->`;

/** Top-level sections, in the order an agent discovers them. */
const SECTIONS = [
  { dir: 'policies', title: 'Policies', columns: ['Load when', 'Paths'] },
  { dir: 'rules', title: 'Rules', columns: ['Load when', 'Paths'] },
  { dir: 'contexts', title: 'Contexts', columns: ['Load when', 'Paths'] },
  { dir: 'references', title: 'References', columns: ['Load when'] },
  { dir: 'skills', title: 'Skills', columns: ['Load when'], flat: true },
  { dir: 'agents', title: 'Agents', columns: ['Load when'] },
  { dir: 'templates', title: 'Templates', columns: ['Load when'] },
];

/** Escapes the one character that would break a Markdown table cell. */
function cell(value) {
  if (value === undefined || value === null) return EM_DASH;
  const text = Array.isArray(value) ? value.join(', ') : String(value);
  const trimmed = text.trim();
  return trimmed === '' ? EM_DASH : trimmed.replace(/\|/g, '\\|');
}

/** The `[[wiki-link]]` for an artifact, relative to the AEP root. */
function link(root, file) {
  return `[[${toPosix(root, file).replace(/\.md$/, '')}]]`;
}

/**
 * The artifacts a section lists.
 *
 * `flat` sections list only what sits directly in the directory. `skills/` is
 * the one that needs it: a skill note is depth reached from its own skill, and
 * listing it here would advertise an entry point that does not exist.
 */
function collect(root, dir, { flat = false } = {}) {
  const full = path.join(root, dir);
  if (!fs.existsSync(full)) return [];
  const files = flat ? topLevel(full) : walk(full).filter((file) => file.endsWith('.md'));
  return files.map((file) => ({ file, ...readArtifact(file) }));
}

/**
 * Local tickets across every effort, flattened into one list.
 *
 * They are indexed together rather than under their efforts because the question
 * a ticket index answers is cross-effort, *what can be worked right now*, and
 * that is read off `status` and `blocked-by`, not off which effort a ticket
 * belongs to. Returns an empty list where a repository keeps its tasks in an
 * external tracker, which is the common case.
 */
function collectTickets(root) {
  const effortsDir = path.join(root, 'efforts');
  if (!fs.existsSync(effortsDir)) return [];

  const tickets = [];
  for (const entry of fs.readdirSync(effortsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const ticketsDir = path.join(effortsDir, entry.name, 'tickets');
    if (!fs.existsSync(ticketsDir)) continue;
    for (const file of walk(ticketsDir).filter((f) => f.endsWith('.md'))) {
      const artifact = readArtifact(file);
      tickets.push({
        file,
        effort: entry.name,
        title: /^#\s+(.+)$/m.exec(artifact.body)?.[1]?.trim() ?? '',
        fields: artifact.fields,
      });
    }
  }
  return tickets;
}

/** Efforts get their own shape: one row per effort, not per file. */
function collectEfforts(root) {
  const effortsDir = path.join(root, 'efforts');
  if (!fs.existsSync(effortsDir)) return [];

  return fs
    .readdirSync(effortsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
    .map((name) => {
      const dir = path.join(effortsDir, name);
      const specFile = path.join(dir, 'spec.md');
      const spec = fs.existsSync(specFile) ? readArtifact(specFile) : null;
      const count = (sub) => {
        const target = path.join(dir, sub);
        return fs.existsSync(target)
          ? walk(target).filter((f) => f.endsWith('.md')).length
          : 0;
      };
      return {
        name,
        status: spec?.fields.status,
        hasSpec: Boolean(spec),
        research: count(path.join('evidence', 'research')),
        prototypes: count(path.join('evidence', 'prototypes')),
        tickets: count('tickets'),
      };
    });
}

function render(root) {
  const protocol = readArtifact(path.join(root, 'protocol.md'));
  const sections = SECTIONS.map((section) => ({
    ...section,
    rows: collect(root, section.dir, { flat: section.flat }),
  }));
  const efforts = collectEfforts(root);

  // The index carries the release the bootstrap declares and nothing else. Its
  // own `date` used to be the newest any artifact declared, which was a field
  // computed from a field that no longer exists on the artifacts it read.
  const out = [];
  out.push('---');
  out.push(`aep: ${protocol.fields.aep ?? protocol.fields.version ?? 'unknown'}`);
  out.push('owner: repository');
  out.push('---');
  out.push('');
  out.push(GENERATED_NOTICE);
  out.push('');
  out.push('# AEP index');
  out.push('');
  out.push(
    `Derived state. The filesystem is authoritative ${EM_DASH} this table only says what`,
  );
  out.push('is there and when it applies, so you can decide what to read.');
  out.push('');
  out.push(`Start at [[protocol]].`);

  for (const section of sections) {
    out.push('');
    out.push(`## ${section.title}`);
    out.push('');
    if (section.rows.length === 0) {
      out.push('_None._');
      continue;
    }
    out.push(`| Artifact | ${section.columns.join(' | ')} | Owner |`);
    out.push(`| --- | ${section.columns.map(() => '---').join(' | ')} | --- |`);
    for (const row of section.rows) {
      const values = section.columns.map((column) => {
        if (column === 'Load when') return cell(row.fields['use-when']);
        if (column === 'Paths') return cell(row.fields.paths);
        return EM_DASH;
      });
      out.push(
        `| ${link(root, row.file)} | ${values.join(' | ')} | ${cell(row.fields.owner)} |`,
      );
    }
  }

  out.push('');
  out.push('## Efforts');
  out.push('');
  if (efforts.length === 0) {
    out.push('_None._');
  } else {
    out.push('| Effort | Status | Spec | Research | Prototypes | Tickets |');
    out.push('| --- | --- | --- | --- | --- | --- |');
    for (const effort of efforts) {
      const spec = effort.hasSpec
        ? `[[efforts/${effort.name}/spec]]`
        : '**missing**';
      out.push(
        `| ${effort.name} | ${cell(effort.status)} | ${spec} | ${effort.research} | ${effort.prototypes} | ${effort.tickets} |`,
      );
    }
  }

  // Only where local tickets exist. A repository using an external tracker gets
  // no section at all rather than an empty one. An empty table would read as
  // "no work", when the truth is "the work is not indexed here".
  const tickets = collectTickets(root);
  if (tickets.length > 0) {
    out.push('');
    out.push('## Tickets');
    out.push('');
    out.push('Local tickets only. Where an external tracker holds the work, it is not mirrored here.');
    out.push('');
    out.push('| Ticket | Effort | Status | Blocked by |');
    out.push('| --- | --- | --- | --- |');
    for (const ticket of tickets) {
      const link = `[[${toPosix(root, ticket.file).replace(/\.md$/, '')}]]`;
      const title = ticket.title ? ` ${cell(ticket.title)}` : '';
      out.push(
        `| ${link}${title} | ${cell(ticket.fields['part-of'] ?? ticket.effort)} | ${cell(ticket.fields.status)} | ${cell(ticket.fields['blocked-by'])} |`,
      );
    }
  }
  out.push('');

  return out.join('\n');
}

function main() {
  const args = process.argv.slice(2);
  const rootArg = args.includes('--root') ? args[args.indexOf('--root') + 1] : null;
  const check = args.includes('--check');

  const root = resolveAepRoot(rootArg, import.meta.url);
  if (!root) {
    process.stderr.write('no .aep/ found. Pass --root, or run from a repository that has one\n');
    process.exit(2);
  }

  const rendered = render(root);
  const target = path.join(root, 'index.md');

  if (check) {
    const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
    if (current === rendered) {
      process.stdout.write('index.md is current\n');
      return;
    }
    process.stderr.write(
      current === null
        ? 'index.md is missing. Run: node .aep/scripts/index.mjs\n'
        : 'index.md is stale. Run: node .aep/scripts/index.mjs\n',
    );
    process.exit(1);
  }

  fs.writeFileSync(target, rendered, 'utf8');
  process.stdout.write(`wrote ${toPosix(path.dirname(root), target)}\n`);
}

main();
